AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2-template'


# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
# AWS管理コンソール、CLI、またはSDKを通じてキーペアを作成し、その名前をCloudFormationスタックの作成時に指定してください。
Parameters:
  PJPrefix:
    Type: String
  KeyPairName:
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instances'
    Type: 'AWS::EC2::KeyPair::KeyName'

# ------------------------------------------------------------#
# EC2 Instance
# ------------------------------------------------------------# 
Resources:
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: 'ami-00d101850e971728d'
      KeyName: !Ref KeyPairName
      InstanceType: 't2.micro'
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue 
            'Fn::Sub': "${PJPrefix}-public-subnet-a"
          GroupSet:
            - !Ref EC2SG
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-EC2"

# EIP
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref EC2

# ------------------------------------------------------------#
# Security Group
# ------------------------------------------------------------# 
  EC2SG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'EC2-sg-cfn'
      GroupDescription: 'Security group for web server'
      VpcId: !ImportValue 
        'Fn::Sub': "${PJPrefix}-vpc"
      SecurityGroupIngress:
        # http
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
        # ssh
        - IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#    
Outputs:
  EC2:
    Value: !Ref EC2
    Export:
      Name: !Sub "${PJPrefix}-EC2"
  EC2SG:
    Value: !Ref EC2SG
    Export:
      Name: !Sub "${PJPrefix}-EC2-sg-cfn"
