AWSTemplateFormatVersion: 2010-09-09
Description: ALB template

Parameters:
  VPCStack:
    Type: String
    Default: VPC
  EC2Stack:
    Type: String
    Default: ec2
    
Resources:
# ALB
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB
      Subnets:
      - !ImportValue PublicSubnet01
      - !ImportValue PublicSubnet02
      SecurityGroups: 
        - !ImportValue EC2SG

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref targetGroup
#TG
  targetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: reaisetech-tg
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      Targets:
      - Id: !ImportValue EC2ID

Outputs:
  FrontLBEndpoint:
    Value: ALB
    Export:
      Name: ALBEndpoint

