AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 template

Resources:
#KeyPair
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: KeyPair
#EC2
  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-00d101850e971728d
      KeyName: !Ref KeyPair
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue PublicSubnet01
          GroupSet:
            - !Ref EC2SG
      UserData: !Base64 |
        #!/bin/bash
        sudo yum install -y git
        sudo amazon-linux-extras install -y nginx1.12
        sudo service nginx start
        
      Tags:
          - Key: Name
            Value: raisetech
#SG
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-sg-cf
      GroupDescription: web
      VpcId: !ImportValue VPC
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # 3000
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
          
Outputs:

  EC2SG:
    Value: !Ref EC2SG
    Export:
      Name: EC2SG

  EC2ID:
        Value: !Ref EC2
        Export:
            Name: EC2ID
